/**
 * Keyword / content cluster map used for internal linking and to plan
 * future SEO landing pages (tools/guides). The shape is intentionally
 * stable so internal-link components and future routing logic can read
 * it directly.
 *
 * - `targetRoute` is the route that already exists today (the cluster's
 *   canonical destination).
 * - `relatedRoutes` is for cross-linking inside the current site map.
 * - `suggestedFutureRoutes` is a forward-looking list of routes that have
 *   not been built yet but are tracked here so authoring stays consistent.
 * - `recommendedInternalLinks` is a curated set of (label, route) pairs
 *   that components can use to build "Related" sections without having to
 *   hardcode anchor text page-by-page.
 */

export type SearchIntent =
  | 'informational'
  | 'transactional'
  | 'navigational'
  | 'commercial';

export interface InternalLinkRecommendation {
  label: string;
  route: string;
  description?: string;
}

export interface KeywordCluster {
  slug: string;
  title: string;
  primaryKeyword: string;
  secondaryKeywords: string[];
  intent: SearchIntent;
  targetRoute: string;
  relatedRoutes: string[];
  suggestedFutureRoutes: string[];
  recommendedInternalLinks: InternalLinkRecommendation[];
}

export const KEYWORD_CLUSTERS: KeywordCluster[] = [
  {
    slug: 'image-conversion',
    title: 'Image conversion',
    primaryKeyword: 'image converter',
    secondaryKeywords: [
      'convert JPG to PNG',
      'convert PNG to WebP',
      'convert HEIC to JPG',
      'convert WebP to JPG',
      'online image converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/image-converter',
    relatedRoutes: [
      '/tools/jpg-converter',
      '/tools/png-converter',
      '/tools/convert-png-to-jpg',
      '/tools/convert-jpg-to-png',
      '/tools/convert-webp-to-png',
      '/tools/convert-png-to-webp',
      '/tools/convert-jpg-to-webp',
      '/tools/convert-webp-to-jpg',
      '/tools/convert-heic-to-jpg',
      '/tools/convert-avif-to-jpg',
      '/tools/svg-converter',
      '/tools/remove-exif-metadata',
      '/tutorials/image/getting-started',
      // '/blog/image/image-optimization-guide', // hidden during AdSense review
      '/how-it-works',
    ],
    suggestedFutureRoutes: [
      '/guides/jpg-vs-png-vs-webp',
    ],
    recommendedInternalLinks: [
      { label: 'Image converter', route: '/tools/image-converter' },
      { label: 'JPG converter', route: '/tools/jpg-converter' },
      { label: 'PNG converter', route: '/tools/png-converter' },
      { label: 'Convert WebP to JPG', route: '/tools/convert-webp-to-jpg' },
      { label: 'Remove EXIF metadata', route: '/tools/remove-exif-metadata' },
      {
        label: 'Image converter tutorial',
        route: '/tutorials/image/getting-started',
      },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Image optimization guide',
      //   route: '/blog/image/image-optimization-guide',
      // },
    ],
  },
  {
    slug: 'image-compression',
    title: 'Image compression',
    primaryKeyword: 'compress images online',
    secondaryKeywords: [
      'shrink image size',
      'reduce JPG file size',
      'compress PNG',
      'WebP compression',
      'lossy vs lossless image compression',
    ],
    intent: 'transactional',
    targetRoute: '/tools/compress-image',
    relatedRoutes: [
      '/tools/image-resizer',
      '/tools/convert-jpg-to-webp',
      '/tools/convert-png-to-webp',
      '/tools/image-converter',
      // '/blog/image/image-optimization-guide', // hidden during AdSense review
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/best-image-compression-format',
    ],
    recommendedInternalLinks: [
      { label: 'Compress image', route: '/tools/compress-image' },
      { label: 'Image resizer', route: '/tools/image-resizer' },
      { label: 'Convert JPG to WebP', route: '/tools/convert-jpg-to-webp' },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Image optimization guide',
      //   route: '/blog/image/image-optimization-guide',
      // },
      {
        label: 'Image converter tutorial',
        route: '/tutorials/image/getting-started',
      },
    ],
  },
  {
    slug: 'exif-metadata-removal',
    title: 'EXIF and image metadata removal',
    primaryKeyword: 'remove EXIF metadata',
    secondaryKeywords: [
      'strip GPS from photos',
      'remove IPTC metadata',
      'photo metadata remover',
      'privacy-safe photo sharing',
    ],
    intent: 'transactional',
    targetRoute: '/tools/remove-exif-metadata',
    relatedRoutes: [
      '/tools/image-converter',
      // '/blog/image/image-optimization-guide', // hidden during AdSense review
      '/tutorials/image/getting-started',
      '/privacy-policy',
    ],
    suggestedFutureRoutes: [
      '/guides/remove-gps-metadata-from-photos',
      '/guides/what-is-exif-metadata',
    ],
    recommendedInternalLinks: [
      { label: 'Remove EXIF metadata', route: '/tools/remove-exif-metadata' },
      { label: 'Image converter', route: '/tools/image-converter' },
      {
        label: 'Image converter tutorial',
        route: '/tutorials/image/getting-started',
      },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Image optimization guide',
      //   route: '/blog/image/image-optimization-guide',
      // },
      { label: 'How it works', route: '/how-it-works' },
    ],
  },
  {
    slug: 'video-conversion',
    title: 'Video conversion',
    primaryKeyword: 'video converter',
    secondaryKeywords: [
      'convert MP4 to WebM',
      'convert MOV to MP4',
      'convert MKV to MP4',
      'convert AVI to MP4',
      'online video converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/video-converter',
    relatedRoutes: [
      '/tools/mp4-converter',
      '/tools/convert-mov-to-mp4',
      '/tools/convert-webm-to-mp4',
      '/tools/convert-avi-to-mp4',
      '/tools/convert-mkv-to-mp4',
      '/tools/convert-mp4-to-webm',
      '/tools/compress-video',
      '/tools/convert-video-to-animated-gif',
      '/tutorials/video/getting-started',
      // '/blog/video/video-compression-guide', // hidden during AdSense review
    ],
    suggestedFutureRoutes: [
      '/guides/best-video-format-for-websites',
      '/guides/mp4-vs-webm',
    ],
    recommendedInternalLinks: [
      { label: 'Video converter', route: '/tools/video-converter' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
      { label: 'Convert MOV to MP4', route: '/tools/convert-mov-to-mp4' },
      { label: 'Convert WebM to MP4', route: '/tools/convert-webm-to-mp4' },
      { label: 'Compress video', route: '/tools/compress-video' },
      { label: 'Convert video to GIF', route: '/tools/convert-video-to-animated-gif' },
      {
        label: 'Video converter tutorial',
        route: '/tutorials/video/getting-started',
      },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Video compression guide',
      //   route: '/blog/video/video-compression-guide',
      // },
    ],
  },
  {
    slug: 'video-compression',
    title: 'Video compression',
    primaryKeyword: 'compress video online',
    secondaryKeywords: [
      'reduce MP4 file size',
      'shrink video for web',
      'video bitrate explained',
      'H.264 vs H.265',
      'compress video for email',
    ],
    intent: 'transactional',
    targetRoute: '/tools/compress-video',
    relatedRoutes: [
      '/tools/video-compressor',
      '/tools/compress-mp4',
      '/tools/video-converter',
      '/tools/resize-video',
      // '/blog/video/video-compression-guide', // hidden during AdSense review
      '/tutorials/video/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/h264-vs-h265',
      '/guides/what-bitrate-should-i-use',
    ],
    recommendedInternalLinks: [
      { label: 'Video compressor', route: '/tools/video-compressor' },
      { label: 'Compress MP4', route: '/tools/compress-mp4' },
      { label: 'Compress video', route: '/tools/compress-video' },
      { label: 'Video converter', route: '/tools/video-converter' },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Video compression guide',
      //   route: '/blog/video/video-compression-guide',
      // },
      {
        label: 'Video converter tutorial',
        route: '/tutorials/video/getting-started',
      },
    ],
  },
  {
    slug: 'video-trim-cut',
    title: 'Video trimming and cutting',
    primaryKeyword: 'video trimmer',
    secondaryKeywords: [
      'trim video online',
      'video cutter',
      'mp4 trimmer',
      'cut video online',
      'cut mp4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/video-trimmer',
    relatedRoutes: [
      '/tools/mp4-trimmer',
      '/tools/video-cutter',
      '/tools/cut-video-online',
      '/tools/video-compressor',
      '/tutorials/video/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/how-to-trim-video-without-reencoding',
    ],
    recommendedInternalLinks: [
      { label: 'Video trimmer', route: '/tools/video-trimmer' },
      { label: 'MP4 trimmer', route: '/tools/mp4-trimmer' },
      { label: 'Video cutter', route: '/tools/video-cutter' },
      { label: 'Cut video online', route: '/tools/cut-video-online' },
    ],
  },
  {
    slug: 'audio-conversion',
    title: 'Audio conversion',
    primaryKeyword: 'audio converter',
    secondaryKeywords: [
      'convert WAV to MP3',
      'convert FLAC to MP3',
      'convert MP3 to OGG',
      'online audio converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/audio-converter',
    relatedRoutes: [
      '/tools/convert-wav-to-mp3',
      '/tools/isolate-vocals-from-song',
      '/tutorials/audio/getting-started',
      // '/blog/audio/audio-quality-guide', // hidden during AdSense review
    ],
    suggestedFutureRoutes: [
      '/tools/convert-flac-to-mp3',
      '/guides/wav-vs-mp3-vs-flac',
    ],
    recommendedInternalLinks: [
      { label: 'Audio converter', route: '/tools/audio-converter' },
      { label: 'Convert WAV to MP3', route: '/tools/convert-wav-to-mp3' },
      { label: 'Isolate vocals from a song', route: '/tools/isolate-vocals-from-song' },
      {
        label: 'Audio converter tutorial',
        route: '/tutorials/audio/getting-started',
      },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Audio quality guide',
      //   route: '/blog/audio/audio-quality-guide',
      // },
    ],
  },
  {
    slug: 'audio-cleanup',
    title: 'Audio cleanup and restoration',
    primaryKeyword: 'remove background noise from audio',
    secondaryKeywords: [
      'clean voice recording',
      'isolate vocals',
      'remove vocals from song',
      'audio denoise online',
      'karaoke maker',
    ],
    intent: 'transactional',
    targetRoute: '/tools/isolate-vocals-from-song',
    relatedRoutes: [
      '/tools/audio-converter',
      '/tools/convert-wav-to-mp3',
      '/tutorials/audio/getting-started',
      // '/blog/audio/audio-quality-guide', // hidden during AdSense review
    ],
    suggestedFutureRoutes: [
      '/tools/remove-background-noise',
      '/tools/remove-vocals',
      '/guides/how-to-clean-podcast-audio',
    ],
    recommendedInternalLinks: [
      { label: 'Isolate vocals from a song', route: '/tools/isolate-vocals-from-song' },
      { label: 'Audio converter', route: '/tools/audio-converter' },
      {
        label: 'Audio converter tutorial',
        route: '/tutorials/audio/getting-started',
      },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Audio quality guide',
      //   route: '/blog/audio/audio-quality-guide',
      // },
    ],
  },
  {
    slug: 'transcription',
    title: 'Transcription and captions',
    primaryKeyword: 'transcribe video online',
    secondaryKeywords: [
      'video to text',
      'audio to text',
      'generate captions',
      'VTT subtitle generator',
      'free transcription',
    ],
    intent: 'transactional',
    targetRoute: '/tools/transcribe-video',
    relatedRoutes: [
      '/tools/video-converter',
      '/tools/audio-converter',
      '/tutorials/video/getting-started',
      '/tutorials/audio/getting-started',
      '/how-it-works',
    ],
    suggestedFutureRoutes: [
      '/tools/transcribe-audio',
      '/guides/how-to-add-captions-to-video',
    ],
    recommendedInternalLinks: [
      { label: 'Transcribe video', route: '/tools/transcribe-video' },
      { label: 'Video converter', route: '/tools/video-converter' },
      {
        label: 'Video converter tutorial',
        route: '/tutorials/video/getting-started',
      },
      {
        label: 'Audio converter tutorial',
        route: '/tutorials/audio/getting-started',
      },
      { label: 'How it works', route: '/how-it-works' },
    ],
  },
  {
    slug: 'ai-summaries',
    title: 'AI summaries and descriptions',
    primaryKeyword: 'AI video summary',
    secondaryKeywords: [
      'summarize video',
      'AI transcript summary',
      'image caption AI',
      'media analysis AI',
    ],
    intent: 'informational',
    targetRoute: '/how-it-works',
    relatedRoutes: [
      '/',
      '/tutorials/video/getting-started',
      '/tutorials/audio/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/ai-video-summaries',
      '/guides/ai-image-descriptions',
    ],
    recommendedInternalLinks: [
      { label: 'How it works', route: '/how-it-works' },
      {
        label: 'Video converter tutorial',
        route: '/tutorials/video/getting-started',
      },
    ],
  },
  {
    slug: 'privacy-safe-media',
    title: 'Privacy-safe media sharing',
    primaryKeyword: 'private file converter',
    secondaryKeywords: [
      'temporary file storage',
      'auto-delete uploads',
      'local AI processing',
      'no third-party AI providers',
    ],
    intent: 'commercial',
    targetRoute: '/how-it-works',
    relatedRoutes: ['/privacy-policy', '/terms-of-service', '/about'],
    suggestedFutureRoutes: [
      '/guides/privacy-safe-media-conversion',
      '/guides/how-uploads-are-deleted',
    ],
    recommendedInternalLinks: [
      { label: 'Privacy Policy', route: '/privacy-policy' },
      { label: 'How it works', route: '/how-it-works' },
      { label: 'About', route: '/about' },
    ],
  },
  {
    slug: 'video-to-gif',
    title: 'Video to GIF conversion',
    primaryKeyword: 'convert video to GIF',
    secondaryKeywords: [
      'video to animated GIF',
      'MP4 to GIF',
      'WebM to GIF',
      'make a GIF from a video',
      'free video to GIF converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-video-to-animated-gif',
    relatedRoutes: [
      '/tools/mp4-to-gif',
      '/tools/video-to-gif',
      '/tools/gif-converter',
      '/tools/compress-video',
      '/tools/video-converter',
      '/tutorials/video/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/best-gif-settings',
      '/tools/convert-video-to-webp',
    ],
    recommendedInternalLinks: [
      { label: 'Convert video to GIF', route: '/tools/convert-video-to-animated-gif' },
      { label: 'MP4 to GIF', route: '/tools/mp4-to-gif' },
      { label: 'Video to GIF', route: '/tools/video-to-gif' },
      { label: 'GIF converter', route: '/tools/gif-converter' },
      { label: 'Compress video', route: '/tools/compress-video' },
      { label: 'Video converter', route: '/tools/video-converter' },
      {
        label: 'Video converter tutorial',
        route: '/tutorials/video/getting-started',
      },
    ],
  },
  {
    slug: 'webp-to-jpg',
    title: 'WebP to JPG conversion',
    primaryKeyword: 'convert WebP to JPG',
    secondaryKeywords: [
      'WebP to JPEG',
      'change WebP to JPG',
      'open WebP file',
      '.webp to .jpg',
      'free WebP converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-webp-to-jpg',
    relatedRoutes: [
      '/tools/convert-webp-to-png',
      '/tools/jpg-converter',
      '/tools/image-converter',
      '/tools/remove-exif-metadata',
      // '/blog/image/image-optimization-guide', // hidden during AdSense review
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: [
      '/guides/why-webp',
    ],
    recommendedInternalLinks: [
      { label: 'Convert WebP to JPG', route: '/tools/convert-webp-to-jpg' },
      { label: 'Image converter', route: '/tools/image-converter' },
      { label: 'Remove EXIF metadata', route: '/tools/remove-exif-metadata' },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Image optimization guide',
      //   route: '/blog/image/image-optimization-guide',
      // },
    ],
  },
  {
    slug: 'png-to-jpg',
    title: 'PNG to JPG conversion',
    primaryKeyword: 'convert PNG to JPG',
    secondaryKeywords: [
      'PNG to JPG',
      'PNG to JPEG',
      'change PNG to JPG',
      '.png to .jpg',
      'PNG to JPG converter free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-png-to-jpg',
    relatedRoutes: [
      '/tools/convert-jpg-to-png',
      '/tools/jpg-converter',
      '/tools/compress-image',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/png-vs-jpg'],
    recommendedInternalLinks: [
      { label: 'Convert PNG to JPG', route: '/tools/convert-png-to-jpg' },
      { label: 'Convert JPG to PNG', route: '/tools/convert-jpg-to-png' },
      { label: 'JPG converter', route: '/tools/jpg-converter' },
      { label: 'Compress image', route: '/tools/compress-image' },
    ],
  },
  {
    slug: 'jpg-to-png',
    title: 'JPG to PNG conversion',
    primaryKeyword: 'convert JPG to PNG',
    secondaryKeywords: [
      'JPG to PNG',
      'JPEG to PNG',
      'change JPG to PNG',
      '.jpg to .png',
      'JPG to PNG converter free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-jpg-to-png',
    relatedRoutes: [
      '/tools/convert-png-to-jpg',
      '/tools/png-converter',
      '/tools/remove-background-from-image',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/png-vs-jpg'],
    recommendedInternalLinks: [
      { label: 'Convert JPG to PNG', route: '/tools/convert-jpg-to-png' },
      { label: 'Convert PNG to JPG', route: '/tools/convert-png-to-jpg' },
      { label: 'PNG converter', route: '/tools/png-converter' },
      { label: 'Remove background from image', route: '/tools/remove-background-from-image' },
    ],
  },
  {
    slug: 'webp-to-png',
    title: 'WebP to PNG conversion',
    primaryKeyword: 'convert WebP to PNG',
    secondaryKeywords: [
      'WebP to PNG',
      'change WebP to PNG',
      '.webp to .png',
      'WebP to PNG transparent',
      'WebP to PNG converter free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-webp-to-png',
    relatedRoutes: [
      '/tools/convert-png-to-webp',
      '/tools/convert-webp-to-jpg',
      '/tools/png-converter',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/why-webp'],
    recommendedInternalLinks: [
      { label: 'Convert WebP to PNG', route: '/tools/convert-webp-to-png' },
      { label: 'Convert PNG to WebP', route: '/tools/convert-png-to-webp' },
      { label: 'Convert WebP to JPG', route: '/tools/convert-webp-to-jpg' },
      { label: 'PNG converter', route: '/tools/png-converter' },
    ],
  },
  {
    slug: 'png-to-webp',
    title: 'PNG to WebP conversion',
    primaryKeyword: 'convert PNG to WebP',
    secondaryKeywords: [
      'PNG to WebP',
      'change PNG to WebP',
      '.png to .webp',
      'PNG to WebP transparent',
      'PNG to WebP converter free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-png-to-webp',
    relatedRoutes: [
      '/tools/convert-webp-to-png',
      '/tools/convert-jpg-to-webp',
      '/tools/compress-image',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/why-webp'],
    recommendedInternalLinks: [
      { label: 'Convert PNG to WebP', route: '/tools/convert-png-to-webp' },
      { label: 'Convert WebP to PNG', route: '/tools/convert-webp-to-png' },
      { label: 'Convert JPG to WebP', route: '/tools/convert-jpg-to-webp' },
      { label: 'Compress image', route: '/tools/compress-image' },
    ],
  },
  {
    slug: 'jpg-to-webp',
    title: 'JPG to WebP conversion',
    primaryKeyword: 'convert JPG to WebP',
    secondaryKeywords: [
      'JPG to WebP',
      'JPEG to WebP',
      'change JPG to WebP',
      '.jpg to .webp',
      'JPG to WebP converter free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-jpg-to-webp',
    relatedRoutes: [
      '/tools/convert-webp-to-jpg',
      '/tools/convert-png-to-webp',
      '/tools/compress-image',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/why-webp'],
    recommendedInternalLinks: [
      { label: 'Convert JPG to WebP', route: '/tools/convert-jpg-to-webp' },
      { label: 'Convert WebP to JPG', route: '/tools/convert-webp-to-jpg' },
      { label: 'Convert PNG to WebP', route: '/tools/convert-png-to-webp' },
      { label: 'Compress image', route: '/tools/compress-image' },
    ],
  },
  {
    slug: 'jpg-converter',
    title: 'JPG converter',
    primaryKeyword: 'JPG converter',
    secondaryKeywords: [
      'convert to JPG',
      'image to JPG',
      'JPEG converter',
      'free JPG converter online',
      'PNG to JPG converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/jpg-converter',
    relatedRoutes: [
      '/tools/convert-png-to-jpg',
      '/tools/convert-webp-to-jpg',
      '/tools/png-converter',
      '/tools/compress-image',
      '/tools/image-converter',
    ],
    suggestedFutureRoutes: ['/guides/jpg-vs-png-vs-webp'],
    recommendedInternalLinks: [
      { label: 'JPG converter', route: '/tools/jpg-converter' },
      { label: 'Convert PNG to JPG', route: '/tools/convert-png-to-jpg' },
      { label: 'Convert WebP to JPG', route: '/tools/convert-webp-to-jpg' },
      { label: 'PNG converter', route: '/tools/png-converter' },
    ],
  },
  {
    slug: 'png-converter',
    title: 'PNG converter',
    primaryKeyword: 'PNG converter',
    secondaryKeywords: [
      'convert to PNG',
      'image to PNG',
      'free PNG converter online',
      'JPG to PNG converter',
      'WebP to PNG converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/png-converter',
    relatedRoutes: [
      '/tools/convert-jpg-to-png',
      '/tools/convert-webp-to-png',
      '/tools/jpg-converter',
      '/tools/remove-background-from-image',
      '/tools/image-converter',
    ],
    suggestedFutureRoutes: ['/guides/jpg-vs-png-vs-webp'],
    recommendedInternalLinks: [
      { label: 'PNG converter', route: '/tools/png-converter' },
      { label: 'Convert JPG to PNG', route: '/tools/convert-jpg-to-png' },
      { label: 'Convert WebP to PNG', route: '/tools/convert-webp-to-png' },
      { label: 'Remove background from image', route: '/tools/remove-background-from-image' },
    ],
  },
  {
    slug: 'image-resizer',
    title: 'Image resizing',
    primaryKeyword: 'resize image online',
    secondaryKeywords: [
      'image resizer',
      'resize photo',
      'change image dimensions',
      'resize JPG',
      'resize PNG online free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/image-resizer',
    relatedRoutes: [
      '/tools/compress-image',
      '/tools/image-converter',
      '/tools/jpg-converter',
      '/tools/png-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/social-image-sizes'],
    recommendedInternalLinks: [
      { label: 'Image resizer', route: '/tools/image-resizer' },
      { label: 'Compress image', route: '/tools/compress-image' },
      { label: 'Image converter', route: '/tools/image-converter' },
    ],
  },
  {
    slug: 'image-compressor',
    title: 'Image compressor',
    primaryKeyword: 'compress image online',
    secondaryKeywords: [
      'image compressor',
      'reduce image file size',
      'shrink image',
      'compress JPG',
      'compress photo online free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/compress-image',
    relatedRoutes: [
      '/tools/image-resizer',
      '/tools/convert-jpg-to-webp',
      '/tools/convert-png-to-webp',
      '/tools/image-converter',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/best-image-compression-format'],
    recommendedInternalLinks: [
      { label: 'Compress image', route: '/tools/compress-image' },
      { label: 'Image resizer', route: '/tools/image-resizer' },
      { label: 'Convert JPG to WebP', route: '/tools/convert-jpg-to-webp' },
    ],
  },
  {
    slug: 'background-remover',
    title: 'Background remover',
    primaryKeyword: 'remove background from image',
    secondaryKeywords: [
      'background remover',
      'remove image background',
      'transparent background maker',
      'erase background from photo',
      'free background remover online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/remove-background-from-image',
    relatedRoutes: [
      '/tools/png-converter',
      '/tools/convert-jpg-to-png',
      '/tools/image-converter',
      '/tools/image-resizer',
      '/tutorials/image/getting-started',
    ],
    suggestedFutureRoutes: ['/guides/transparent-product-photos'],
    recommendedInternalLinks: [
      { label: 'Remove background from image', route: '/tools/remove-background-from-image' },
      { label: 'PNG converter', route: '/tools/png-converter' },
      { label: 'Image converter', route: '/tools/image-converter' },
    ],
  },
  {
    slug: 'image-to-pdf',
    title: 'Image to PDF conversion',
    primaryKeyword: 'image to pdf',
    secondaryKeywords: [
      'image to pdf converter',
      'jpg png to pdf',
      'photo to pdf',
      'convert image to pdf',
      'picture to pdf',
    ],
    intent: 'transactional',
    targetRoute: '/tools/image-to-pdf',
    relatedRoutes: [
      '/tools/convert-jpg-to-pdf',
      '/tools/convert-png-to-pdf',
      '/tools/pdf-converter',
      '/tools/image-converter',
    ],
    suggestedFutureRoutes: ['/tools/merge-images-to-pdf'],
    recommendedInternalLinks: [
      { label: 'Image to PDF', route: '/tools/image-to-pdf' },
      { label: 'Convert JPG to PDF', route: '/tools/convert-jpg-to-pdf' },
      { label: 'Convert PNG to PDF', route: '/tools/convert-png-to-pdf' },
      { label: 'PDF converter', route: '/tools/pdf-converter' },
    ],
  },
  {
    slug: 'jpg-to-pdf',
    title: 'JPG to PDF conversion',
    primaryKeyword: 'jpg to pdf',
    secondaryKeywords: [
      'jpg to pdf converter',
      'convert jpg to pdf',
      'jpeg to pdf',
      '.jpg to .pdf',
      'photo to pdf',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-jpg-to-pdf',
    relatedRoutes: [
      '/tools/convert-png-to-pdf',
      '/tools/image-to-pdf',
      '/tools/jpg-converter',
      '/tools/pdf-to-jpg',
    ],
    suggestedFutureRoutes: ['/guides/jpg-vs-pdf'],
    recommendedInternalLinks: [
      { label: 'Convert JPG to PDF', route: '/tools/convert-jpg-to-pdf' },
      { label: 'Convert PNG to PDF', route: '/tools/convert-png-to-pdf' },
      { label: 'Image to PDF', route: '/tools/image-to-pdf' },
      { label: 'JPG converter', route: '/tools/jpg-converter' },
    ],
  },
  {
    slug: 'png-to-pdf',
    title: 'PNG to PDF conversion',
    primaryKeyword: 'png to pdf',
    secondaryKeywords: [
      'png to pdf converter',
      'convert png to pdf',
      '.png to .pdf',
      'screenshot to pdf',
      'image to pdf',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-png-to-pdf',
    relatedRoutes: [
      '/tools/convert-jpg-to-pdf',
      '/tools/image-to-pdf',
      '/tools/png-converter',
      '/tools/pdf-to-png',
    ],
    suggestedFutureRoutes: ['/guides/png-vs-pdf'],
    recommendedInternalLinks: [
      { label: 'Convert PNG to PDF', route: '/tools/convert-png-to-pdf' },
      { label: 'Convert JPG to PDF', route: '/tools/convert-jpg-to-pdf' },
      { label: 'Image to PDF', route: '/tools/image-to-pdf' },
      { label: 'PNG converter', route: '/tools/png-converter' },
    ],
  },
  {
    slug: 'pdf-to-jpg',
    title: 'PDF to JPG conversion',
    primaryKeyword: 'pdf to jpg',
    secondaryKeywords: [
      'pdf to image',
      'pdf page to jpg',
      'convert pdf to jpg',
      'pdf to jpeg',
      'pdf to jpg converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/pdf-to-jpg',
    relatedRoutes: [
      '/tools/pdf-to-png',
      '/tools/pdf-converter',
      '/tools/image-converter',
      '/tools/image-to-pdf',
    ],
    suggestedFutureRoutes: ['/guides/pdf-to-image-tips'],
    recommendedInternalLinks: [
      { label: 'PDF to JPG', route: '/tools/pdf-to-jpg' },
      { label: 'PDF to PNG', route: '/tools/pdf-to-png' },
      { label: 'PDF converter', route: '/tools/pdf-converter' },
      { label: 'Image converter', route: '/tools/image-converter' },
    ],
  },
  {
    slug: 'pdf-to-png',
    title: 'PDF to PNG conversion',
    primaryKeyword: 'pdf to png',
    secondaryKeywords: [
      'pdf page to png',
      'convert pdf to png',
      'pdf to image',
      'pdf to png converter',
      'pdf to transparent png',
    ],
    intent: 'transactional',
    targetRoute: '/tools/pdf-to-png',
    relatedRoutes: [
      '/tools/pdf-to-jpg',
      '/tools/pdf-converter',
      '/tools/image-converter',
      '/tools/image-to-pdf',
    ],
    suggestedFutureRoutes: ['/guides/pdf-to-image-tips'],
    recommendedInternalLinks: [
      { label: 'PDF to PNG', route: '/tools/pdf-to-png' },
      { label: 'PDF to JPG', route: '/tools/pdf-to-jpg' },
      { label: 'PDF converter', route: '/tools/pdf-converter' },
      { label: 'Image converter', route: '/tools/image-converter' },
    ],
  },
  {
    slug: 'pdf-converter',
    title: 'PDF conversion',
    primaryKeyword: 'pdf converter',
    secondaryKeywords: [
      'online pdf converter',
      'convert pdf to image',
      'convert image to pdf',
      'pdf to jpg',
      'free pdf converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/pdf-converter',
    relatedRoutes: [
      '/tools/pdf-to-jpg',
      '/tools/pdf-to-png',
      '/tools/image-to-pdf',
      '/tools/convert-jpg-to-pdf',
      '/tools/convert-png-to-pdf',
    ],
    suggestedFutureRoutes: ['/tools/merge-pdf', '/tools/split-pdf'],
    recommendedInternalLinks: [
      { label: 'PDF converter', route: '/tools/pdf-converter' },
      { label: 'PDF to JPG', route: '/tools/pdf-to-jpg' },
      { label: 'PDF to PNG', route: '/tools/pdf-to-png' },
      { label: 'Image to PDF', route: '/tools/image-to-pdf' },
    ],
  },
  {
    slug: 'heic-to-jpg',
    title: 'HEIC to JPG conversion',
    primaryKeyword: 'heic to jpg',
    secondaryKeywords: [
      'convert heic to jpg',
      'heic to jpeg',
      'iphone photo to jpg',
      '.heic to .jpg',
      'heic converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-heic-to-jpg',
    relatedRoutes: [
      '/tools/jpg-converter',
      '/tools/convert-avif-to-jpg',
      '/tools/image-converter',
      '/tools/compress-image',
    ],
    suggestedFutureRoutes: ['/tools/convert-heic-to-png'],
    recommendedInternalLinks: [
      { label: 'Convert HEIC to JPG', route: '/tools/convert-heic-to-jpg' },
      { label: 'JPG converter', route: '/tools/jpg-converter' },
      { label: 'Image converter', route: '/tools/image-converter' },
    ],
  },
  {
    slug: 'avif-to-jpg',
    title: 'AVIF to JPG conversion',
    primaryKeyword: 'avif to jpg',
    secondaryKeywords: [
      'convert avif to jpg',
      'avif to jpeg',
      '.avif to .jpg',
      'avif converter',
      'open avif file',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-avif-to-jpg',
    relatedRoutes: [
      '/tools/convert-avif-to-png',
      '/tools/jpg-converter',
      '/tools/image-converter',
      '/tools/convert-heic-to-jpg',
    ],
    suggestedFutureRoutes: ['/guides/avif-vs-webp'],
    recommendedInternalLinks: [
      { label: 'Convert AVIF to JPG', route: '/tools/convert-avif-to-jpg' },
      { label: 'Convert AVIF to PNG', route: '/tools/convert-avif-to-png' },
      { label: 'JPG converter', route: '/tools/jpg-converter' },
    ],
  },
  {
    slug: 'avif-to-png',
    title: 'AVIF to PNG conversion',
    primaryKeyword: 'avif to png',
    secondaryKeywords: [
      'convert avif to png',
      '.avif to .png',
      'avif to transparent png',
      'avif converter',
      'avif to png online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-avif-to-png',
    relatedRoutes: [
      '/tools/convert-avif-to-jpg',
      '/tools/png-converter',
      '/tools/image-converter',
      '/tools/remove-background-from-image',
    ],
    suggestedFutureRoutes: ['/guides/avif-vs-webp'],
    recommendedInternalLinks: [
      { label: 'Convert AVIF to PNG', route: '/tools/convert-avif-to-png' },
      { label: 'Convert AVIF to JPG', route: '/tools/convert-avif-to-jpg' },
      { label: 'PNG converter', route: '/tools/png-converter' },
    ],
  },
  {
    slug: 'svg-to-png',
    title: 'SVG to PNG conversion',
    primaryKeyword: 'svg to png',
    secondaryKeywords: [
      'convert svg to png',
      'svg to png converter',
      'rasterize svg',
      '.svg to .png',
      'svg to image',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-svg-to-png',
    relatedRoutes: [
      '/tools/convert-png-to-svg',
      '/tools/svg-converter',
      '/tools/png-converter',
      '/tools/png-to-ico',
    ],
    suggestedFutureRoutes: ['/tools/convert-svg-to-pdf'],
    recommendedInternalLinks: [
      { label: 'Convert SVG to PNG', route: '/tools/convert-svg-to-png' },
      { label: 'Convert PNG to SVG', route: '/tools/convert-png-to-svg' },
      { label: 'SVG converter', route: '/tools/svg-converter' },
    ],
  },
  {
    slug: 'png-to-svg',
    title: 'PNG to SVG vectorization',
    primaryKeyword: 'png to svg',
    secondaryKeywords: [
      'convert png to svg',
      'vectorize png',
      'png to svg converter',
      'image to vector',
      'png to vector',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-png-to-svg',
    relatedRoutes: [
      '/tools/convert-svg-to-png',
      '/tools/svg-converter',
      '/tools/png-converter',
      '/tools/png-to-ico',
    ],
    suggestedFutureRoutes: ['/guides/how-vectorization-works'],
    recommendedInternalLinks: [
      { label: 'Convert PNG to SVG', route: '/tools/convert-png-to-svg' },
      { label: 'Convert SVG to PNG', route: '/tools/convert-svg-to-png' },
      { label: 'SVG converter', route: '/tools/svg-converter' },
    ],
  },
  {
    slug: 'png-to-ico',
    title: 'PNG to ICO conversion',
    primaryKeyword: 'png to ico',
    secondaryKeywords: [
      'convert png to ico',
      'png to favicon',
      'favicon generator',
      '.png to .ico',
      'create ico file',
    ],
    intent: 'transactional',
    targetRoute: '/tools/png-to-ico',
    relatedRoutes: [
      '/tools/png-converter',
      '/tools/convert-svg-to-png',
      '/tools/image-resizer',
      '/tools/image-converter',
    ],
    suggestedFutureRoutes: ['/tools/favicon-generator'],
    recommendedInternalLinks: [
      { label: 'PNG to ICO', route: '/tools/png-to-ico' },
      { label: 'PNG converter', route: '/tools/png-converter' },
      { label: 'Image resizer', route: '/tools/image-resizer' },
    ],
  },
  {
    slug: 'svg-converter',
    title: 'SVG conversion',
    primaryKeyword: 'svg converter',
    secondaryKeywords: [
      'online svg converter',
      'svg to png',
      'png to svg',
      'convert svg',
      'free svg converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/svg-converter',
    relatedRoutes: [
      '/tools/convert-svg-to-png',
      '/tools/convert-png-to-svg',
      '/tools/png-to-ico',
      '/tools/png-converter',
    ],
    suggestedFutureRoutes: ['/tools/convert-svg-to-pdf'],
    recommendedInternalLinks: [
      { label: 'SVG converter', route: '/tools/svg-converter' },
      { label: 'Convert SVG to PNG', route: '/tools/convert-svg-to-png' },
      { label: 'Convert PNG to SVG', route: '/tools/convert-png-to-svg' },
    ],
  },
  {
    slug: 'wav-to-mp3',
    title: 'WAV to MP3 conversion',
    primaryKeyword: 'convert WAV to MP3',
    secondaryKeywords: [
      'WAV to MP3 converter',
      'change WAV to MP3',
      'compress WAV',
      '.wav to .mp3',
      'WAV file to MP3 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-wav-to-mp3',
    relatedRoutes: [
      '/tools/audio-converter',
      '/tools/isolate-vocals-from-song',
      '/tutorials/audio/getting-started',
      // '/blog/audio/audio-quality-guide', // hidden during AdSense review
    ],
    suggestedFutureRoutes: [
      '/tools/convert-flac-to-mp3',
      '/tools/convert-m4a-to-mp3',
    ],
    recommendedInternalLinks: [
      { label: 'Convert WAV to MP3', route: '/tools/convert-wav-to-mp3' },
      { label: 'Audio converter', route: '/tools/audio-converter' },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Audio quality guide',
      //   route: '/blog/audio/audio-quality-guide',
      // },
    ],
  },
  {
    slug: 'isolate-vocals',
    title: 'Vocal isolation',
    primaryKeyword: 'isolate vocals from a song',
    secondaryKeywords: [
      'extract vocals from song',
      'vocal isolator online',
      'AI vocal extractor',
      'separate vocals from music',
      'acapella maker',
    ],
    intent: 'transactional',
    targetRoute: '/tools/isolate-vocals-from-song',
    relatedRoutes: [
      '/tools/audio-converter',
      '/tools/convert-wav-to-mp3',
      '/tutorials/audio/getting-started',
      // '/blog/audio/audio-quality-guide', // hidden during AdSense review
    ],
    suggestedFutureRoutes: [
      '/tools/remove-vocals',
      '/tools/remove-background-noise',
      '/guides/how-source-separation-works',
    ],
    recommendedInternalLinks: [
      { label: 'Isolate vocals from a song', route: '/tools/isolate-vocals-from-song' },
      { label: 'Audio converter', route: '/tools/audio-converter' },
      { label: 'Convert WAV to MP3', route: '/tools/convert-wav-to-mp3' },
      // Hidden during AdSense review — re-enable when the blog returns.
      // {
      //   label: 'Audio quality guide',
      //   route: '/blog/audio/audio-quality-guide',
      // },
    ],
  },
  {
    slug: 'srt-generator',
    title: 'SRT generator',
    primaryKeyword: 'SRT generator',
    secondaryKeywords: [
      'generate SRT from video',
      'video to SRT',
      'audio to SRT',
      'free SRT generator',
      'create SRT file from video',
      'subtitle generator online',
      'MP4 to SRT',
    ],
    intent: 'transactional',
    targetRoute: '/tools/srt-generator',
    relatedRoutes: [
      '/tools/caption-translator',
      '/tools/extract-audio-from-video',
      '/tools/transcribe-video',
      '/tools/transcode-to-hls',
      '/tools/transcode-to-dash',
    ],
    suggestedFutureRoutes: [
      '/guides/srt-vs-vtt',
      '/tools/burn-subtitles-into-video',
    ],
    recommendedInternalLinks: [
      { label: 'SRT generator', route: '/tools/srt-generator' },
      { label: 'Caption translator', route: '/tools/caption-translator' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Transcribe a video', route: '/tools/transcribe-video' },
    ],
  },
  {
    slug: 'caption-translator',
    title: 'Caption translator',
    primaryKeyword: 'caption translator',
    secondaryKeywords: [
      'translate SRT file',
      'translate VTT file',
      'subtitle translator',
      'translate subtitles online',
      'SRT translator',
      'VTT translator',
      'caption translator online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/caption-translator',
    relatedRoutes: [
      '/tools/srt-generator',
      '/tools/extract-audio-from-video',
      '/tools/stitch-audio-to-video',
      '/tools/transcode-to-hls',
      '/tools/transcode-to-dash',
    ],
    suggestedFutureRoutes: ['/guides/translating-youtube-captions'],
    recommendedInternalLinks: [
      { label: 'Caption translator', route: '/tools/caption-translator' },
      { label: 'SRT generator', route: '/tools/srt-generator' },
      { label: 'Stitch audio to video', route: '/tools/stitch-audio-to-video' },
    ],
  },
  {
    slug: 'audio-waveform-generator',
    title: 'Audio waveform generator',
    primaryKeyword: 'audio waveform generator',
    secondaryKeywords: [
      'create waveform from audio',
      'MP3 waveform generator',
      'podcast waveform video',
      'podcast waveform image',
      'sound wave video generator',
      'audio visualizer generator',
      'waveform video maker',
    ],
    intent: 'transactional',
    targetRoute: '/tools/audio-waveform-generator',
    relatedRoutes: [
      '/tools/extract-audio-from-video',
      '/tools/srt-generator',
      '/tools/stitch-audio-to-video',
    ],
    suggestedFutureRoutes: ['/guides/audiogram-best-practices'],
    recommendedInternalLinks: [
      { label: 'Audio waveform generator', route: '/tools/audio-waveform-generator' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'SRT generator', route: '/tools/srt-generator' },
    ],
  },
  {
    slug: 'extract-audio-from-video',
    title: 'Extract audio from video',
    primaryKeyword: 'extract audio from video',
    secondaryKeywords: [
      'video to MP3',
      'convert video to audio',
      'save audio from video',
      'MP4 to MP3',
      'MOV to WAV',
      'extract audio MP4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/extract-audio-from-video',
    relatedRoutes: [
      '/tools/srt-generator',
      '/tools/audio-waveform-generator',
      '/tools/stitch-audio-to-video',
    ],
    suggestedFutureRoutes: ['/guides/podcast-from-video'],
    recommendedInternalLinks: [
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Audio waveform generator', route: '/tools/audio-waveform-generator' },
      { label: 'SRT generator', route: '/tools/srt-generator' },
    ],
  },
  {
    slug: 'extract-video-only-from-video',
    title: 'Remove audio from video',
    primaryKeyword: 'remove audio from video',
    secondaryKeywords: [
      'mute video online',
      'extract video without audio',
      'video only extractor',
      'delete audio track from video',
      'silent video maker',
      'strip audio from MP4',
    ],
    intent: 'transactional',
    targetRoute: '/tools/extract-video-only-from-video',
    relatedRoutes: [
      '/tools/extract-audio-from-video',
      '/tools/stitch-audio-to-video',
      '/tools/extract-frames-from-video',
    ],
    suggestedFutureRoutes: ['/guides/social-silent-video'],
    recommendedInternalLinks: [
      { label: 'Remove audio from video', route: '/tools/extract-video-only-from-video' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Stitch audio to video', route: '/tools/stitch-audio-to-video' },
    ],
  },
  {
    slug: 'extract-frames-from-video',
    title: 'Extract frames from video',
    primaryKeyword: 'extract frames from video',
    secondaryKeywords: [
      'video to images',
      'video frame extractor',
      'capture still images from video',
      'export frames from video',
      'video to JPG online',
      'extract every Nth frame',
    ],
    intent: 'transactional',
    targetRoute: '/tools/extract-frames-from-video',
    relatedRoutes: [
      '/tools/extract-audio-from-video',
      '/tools/srt-generator',
      '/tools/extract-video-only-from-video',
    ],
    suggestedFutureRoutes: ['/guides/thumbnails-from-video'],
    recommendedInternalLinks: [
      { label: 'Extract frames from video', route: '/tools/extract-frames-from-video' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Remove audio from video', route: '/tools/extract-video-only-from-video' },
    ],
  },
  {
    slug: 'stitch-audio-to-video',
    title: 'Stitch audio to video',
    primaryKeyword: 'add audio to video',
    secondaryKeywords: [
      'add music to video',
      'add voiceover to video',
      'combine audio and video',
      'replace audio in video',
      'mix audio with video',
      'add narration to video',
    ],
    intent: 'transactional',
    targetRoute: '/tools/stitch-audio-to-video',
    relatedRoutes: [
      '/tools/extract-audio-from-video',
      '/tools/extract-video-only-from-video',
      '/tools/audio-waveform-generator',
    ],
    suggestedFutureRoutes: ['/guides/voiceover-workflow'],
    recommendedInternalLinks: [
      { label: 'Stitch audio to video', route: '/tools/stitch-audio-to-video' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Remove audio from video', route: '/tools/extract-video-only-from-video' },
    ],
  },

  // ----------------------------------------------------------------------- VIDEO SEO BATCH 1 CLUSTERS
  {
    slug: 'mp4-conversion',
    title: 'MP4 conversion',
    primaryKeyword: 'mp4 converter',
    secondaryKeywords: [
      'mp4 converter online',
      'free mp4 converter',
      'video to mp4',
      'convert to mp4',
    ],
    intent: 'transactional',
    targetRoute: '/tools/mp4-converter',
    relatedRoutes: [
      '/tools/convert-mov-to-mp4',
      '/tools/convert-webm-to-mp4',
      '/tools/convert-avi-to-mp4',
      '/tools/convert-mkv-to-mp4',
      '/tools/convert-mp4-to-webm',
      '/tools/video-converter',
      '/tools/compress-video',
    ],
    suggestedFutureRoutes: ['/guides/mp4-vs-webm'],
    recommendedInternalLinks: [
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
      { label: 'Convert MOV to MP4', route: '/tools/convert-mov-to-mp4' },
      { label: 'Convert WebM to MP4', route: '/tools/convert-webm-to-mp4' },
      { label: 'Video converter', route: '/tools/video-converter' },
    ],
  },
  {
    slug: 'mov-to-mp4',
    title: 'MOV to MP4 conversion',
    primaryKeyword: 'mov to mp4',
    secondaryKeywords: [
      'mov to mp4 converter',
      'convert mov to mp4',
      'quicktime to mp4',
      'iphone mov to mp4',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-mov-to-mp4',
    relatedRoutes: [
      '/tools/mp4-converter',
      '/tools/video-converter',
      '/tools/compress-video',
    ],
    suggestedFutureRoutes: ['/guides/why-wont-my-mov-play'],
    recommendedInternalLinks: [
      { label: 'Convert MOV to MP4', route: '/tools/convert-mov-to-mp4' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
      { label: 'Compress video', route: '/tools/compress-video' },
    ],
  },
  {
    slug: 'webm-to-mp4',
    title: 'WebM to MP4 conversion',
    primaryKeyword: 'webm to mp4',
    secondaryKeywords: [
      'webm to mp4 converter',
      'convert webm to mp4',
      'webm to mp4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-webm-to-mp4',
    relatedRoutes: [
      '/tools/mp4-converter',
      '/tools/convert-mp4-to-webm',
      '/tools/video-converter',
    ],
    suggestedFutureRoutes: ['/guides/mp4-vs-webm'],
    recommendedInternalLinks: [
      { label: 'Convert WebM to MP4', route: '/tools/convert-webm-to-mp4' },
      { label: 'Convert MP4 to WebM', route: '/tools/convert-mp4-to-webm' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
    ],
  },
  {
    slug: 'avi-to-mp4',
    title: 'AVI to MP4 conversion',
    primaryKeyword: 'avi to mp4',
    secondaryKeywords: [
      'avi to mp4 converter',
      'convert avi to mp4',
      'avi to mp4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-avi-to-mp4',
    relatedRoutes: [
      '/tools/mp4-converter',
      '/tools/video-converter',
      '/tools/compress-video',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Convert AVI to MP4', route: '/tools/convert-avi-to-mp4' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
      { label: 'Compress video', route: '/tools/compress-video' },
    ],
  },
  {
    slug: 'mkv-to-mp4',
    title: 'MKV to MP4 conversion',
    primaryKeyword: 'mkv to mp4',
    secondaryKeywords: [
      'mkv to mp4 converter',
      'convert mkv to mp4',
      'matroska to mp4',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-mkv-to-mp4',
    relatedRoutes: [
      '/tools/mp4-converter',
      '/tools/video-converter',
      '/tools/compress-video',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Convert MKV to MP4', route: '/tools/convert-mkv-to-mp4' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
      { label: 'Video converter', route: '/tools/video-converter' },
    ],
  },
  {
    slug: 'mp4-to-webm',
    title: 'MP4 to WebM conversion',
    primaryKeyword: 'mp4 to webm',
    secondaryKeywords: [
      'mp4 to webm converter',
      'convert mp4 to webm',
      'mp4 to webm online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/convert-mp4-to-webm',
    relatedRoutes: [
      '/tools/convert-webm-to-mp4',
      '/tools/mp4-converter',
      '/tools/video-converter',
    ],
    suggestedFutureRoutes: ['/guides/mp4-vs-webm'],
    recommendedInternalLinks: [
      { label: 'Convert MP4 to WebM', route: '/tools/convert-mp4-to-webm' },
      { label: 'Convert WebM to MP4', route: '/tools/convert-webm-to-mp4' },
      { label: 'Video converter', route: '/tools/video-converter' },
    ],
  },
  {
    slug: 'mp4-to-mp3',
    title: 'MP4 to MP3 conversion',
    primaryKeyword: 'mp4 to mp3',
    secondaryKeywords: [
      'mp4 to mp3 converter',
      'extract mp3 from mp4',
      'convert mp4 to mp3',
    ],
    intent: 'transactional',
    targetRoute: '/tools/mp4-to-mp3',
    relatedRoutes: [
      '/tools/video-to-mp3',
      '/tools/extract-audio-from-video',
      '/tools/audio-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'MP4 to MP3', route: '/tools/mp4-to-mp3' },
      { label: 'Video to MP3', route: '/tools/video-to-mp3' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
    ],
  },
  {
    slug: 'video-to-mp3',
    title: 'Video to MP3 conversion',
    primaryKeyword: 'video to mp3',
    secondaryKeywords: [
      'video to mp3 converter',
      'extract audio from video',
      'convert video to mp3',
    ],
    intent: 'transactional',
    targetRoute: '/tools/video-to-mp3',
    relatedRoutes: [
      '/tools/mp4-to-mp3',
      '/tools/extract-audio-from-video',
      '/tools/audio-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Video to MP3', route: '/tools/video-to-mp3' },
      { label: 'MP4 to MP3', route: '/tools/mp4-to-mp3' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
    ],
  },
  {
    slug: 'mp4-to-gif',
    title: 'MP4 to GIF conversion',
    primaryKeyword: 'mp4 to gif',
    secondaryKeywords: [
      'mp4 to gif converter',
      'convert mp4 to gif',
      'mp4 to gif online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/mp4-to-gif',
    relatedRoutes: [
      '/tools/video-to-gif',
      '/tools/gif-converter',
      '/tools/convert-video-to-animated-gif',
    ],
    suggestedFutureRoutes: ['/guides/best-gif-settings'],
    recommendedInternalLinks: [
      { label: 'MP4 to GIF', route: '/tools/mp4-to-gif' },
      { label: 'Video to GIF', route: '/tools/video-to-gif' },
      { label: 'GIF converter', route: '/tools/gif-converter' },
    ],
  },
  {
    slug: 'gif-conversion',
    title: 'GIF conversion',
    primaryKeyword: 'gif converter',
    secondaryKeywords: [
      'video to gif',
      'mp4 to gif',
      'gif maker',
      'animated gif converter',
    ],
    intent: 'transactional',
    targetRoute: '/tools/gif-converter',
    relatedRoutes: [
      '/tools/mp4-to-gif',
      '/tools/video-to-gif',
      '/tools/convert-video-to-animated-gif',
      '/tools/image-converter',
    ],
    suggestedFutureRoutes: ['/guides/best-gif-settings'],
    recommendedInternalLinks: [
      { label: 'GIF converter', route: '/tools/gif-converter' },
      { label: 'MP4 to GIF', route: '/tools/mp4-to-gif' },
      { label: 'Video to GIF', route: '/tools/video-to-gif' },
    ],
  },

  // ----------------------------------------------------------------------- VIDEO SEO BATCH 2 CLUSTERS
  {
    slug: 'video-compressor',
    title: 'Video compressor',
    primaryKeyword: 'video compressor',
    secondaryKeywords: [
      'compress video',
      'compress video online',
      'reduce video size',
      'free video compressor',
    ],
    intent: 'transactional',
    targetRoute: '/tools/video-compressor',
    relatedRoutes: [
      '/tools/compress-mp4',
      '/tools/compress-video',
      '/tools/video-converter',
      '/tools/resize-video',
    ],
    suggestedFutureRoutes: ['/guides/h264-vs-h265'],
    recommendedInternalLinks: [
      { label: 'Video compressor', route: '/tools/video-compressor' },
      { label: 'Compress MP4', route: '/tools/compress-mp4' },
      { label: 'Resize video', route: '/tools/resize-video' },
    ],
  },
  {
    slug: 'mp4-compressor',
    title: 'MP4 compressor',
    primaryKeyword: 'compress mp4',
    secondaryKeywords: [
      'mp4 compressor',
      'reduce mp4 file size',
      'shrink mp4',
      'compress mp4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/compress-mp4',
    relatedRoutes: [
      '/tools/video-compressor',
      '/tools/mp4-converter',
      '/tools/mp4-trimmer',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Compress MP4', route: '/tools/compress-mp4' },
      { label: 'Video compressor', route: '/tools/video-compressor' },
      { label: 'MP4 converter', route: '/tools/mp4-converter' },
    ],
  },
  {
    slug: 'mp4-trimmer',
    title: 'MP4 trimmer',
    primaryKeyword: 'mp4 trimmer',
    secondaryKeywords: [
      'trim mp4',
      'mp4 cutter',
      'cut mp4 online',
    ],
    intent: 'transactional',
    targetRoute: '/tools/mp4-trimmer',
    relatedRoutes: [
      '/tools/video-trimmer',
      '/tools/compress-mp4',
      '/tools/mp4-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'MP4 trimmer', route: '/tools/mp4-trimmer' },
      { label: 'Video trimmer', route: '/tools/video-trimmer' },
      { label: 'Compress MP4', route: '/tools/compress-mp4' },
    ],
  },
  {
    slug: 'video-cutter',
    title: 'Video cutter',
    primaryKeyword: 'video cutter',
    secondaryKeywords: [
      'cut video online',
      'online video cutter',
      'cut video free',
    ],
    intent: 'transactional',
    targetRoute: '/tools/video-cutter',
    relatedRoutes: [
      '/tools/video-trimmer',
      '/tools/cut-video-online',
      '/tools/mp4-trimmer',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Video cutter', route: '/tools/video-cutter' },
      { label: 'Cut video online', route: '/tools/cut-video-online' },
      { label: 'Video trimmer', route: '/tools/video-trimmer' },
    ],
  },
  {
    slug: 'crop-video',
    title: 'Crop video',
    primaryKeyword: 'crop video',
    secondaryKeywords: [
      'video cropper',
      'crop video online',
      'crop mp4',
    ],
    intent: 'transactional',
    targetRoute: '/tools/crop-video',
    relatedRoutes: [
      '/tools/resize-video',
      '/tools/rotate-video',
      '/tools/video-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Crop video', route: '/tools/crop-video' },
      { label: 'Resize video', route: '/tools/resize-video' },
      { label: 'Rotate video', route: '/tools/rotate-video' },
    ],
  },
  {
    slug: 'resize-video',
    title: 'Resize video',
    primaryKeyword: 'resize video',
    secondaryKeywords: [
      'video resizer',
      'change video resolution',
      'resize video online',
      'scale video',
    ],
    intent: 'transactional',
    targetRoute: '/tools/resize-video',
    relatedRoutes: [
      '/tools/crop-video',
      '/tools/video-compressor',
      '/tools/mp4-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Resize video', route: '/tools/resize-video' },
      { label: 'Crop video', route: '/tools/crop-video' },
      { label: 'Video compressor', route: '/tools/video-compressor' },
    ],
  },
  {
    slug: 'rotate-video',
    title: 'Rotate video',
    primaryKeyword: 'rotate video',
    secondaryKeywords: [
      'rotate mp4',
      'rotate video online',
      'fix sideways video',
      'flip video',
    ],
    intent: 'transactional',
    targetRoute: '/tools/rotate-video',
    relatedRoutes: [
      '/tools/crop-video',
      '/tools/resize-video',
      '/tools/video-converter',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Rotate video', route: '/tools/rotate-video' },
      { label: 'Crop video', route: '/tools/crop-video' },
      { label: 'Resize video', route: '/tools/resize-video' },
    ],
  },
  {
    slug: 'remove-audio-from-video',
    title: 'Remove audio from video',
    primaryKeyword: 'remove audio from video',
    secondaryKeywords: [
      'mute video',
      'remove sound from video',
      'silence video',
      'strip audio from video',
    ],
    intent: 'transactional',
    targetRoute: '/tools/remove-audio-from-video',
    relatedRoutes: [
      '/tools/extract-video-only-from-video',
      '/tools/extract-audio-from-video',
      '/tools/video-compressor',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Remove audio from video', route: '/tools/remove-audio-from-video' },
      { label: 'Extract audio from video', route: '/tools/extract-audio-from-video' },
      { label: 'Stitch audio to video', route: '/tools/stitch-audio-to-video' },
    ],
  },
  {
    slug: 'mute-video',
    title: 'Mute video',
    primaryKeyword: 'mute video',
    secondaryKeywords: [
      'mute video online',
      'remove sound from video',
      'silence a video',
    ],
    intent: 'transactional',
    targetRoute: '/tools/remove-audio-from-video',
    relatedRoutes: [
      '/tools/remove-audio-from-video',
      '/tools/extract-video-only-from-video',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'Mute / remove audio', route: '/tools/remove-audio-from-video' },
      { label: 'Extract video without audio', route: '/tools/extract-video-only-from-video' },
    ],
  },
  {
    slug: 'ai-image-restoration',
    title: 'AI Image Restoration & Upscaling',
    primaryKeyword: 'AI image restoration',
    secondaryKeywords: [
      'AI image upscaler',
      'restore old photo AI',
      'enhance low resolution image',
      'upscale image to 4k',
      'upscale image to 8k',
      'AI photo restoration online',
      'fix blurry photo AI',
      'enhance face in photo',
      'CCTV image enhancement',
      'remove jpeg artifacts AI',
      'denoise image AI',
      'deblur image AI',
    ],
    intent: 'transactional',
    targetRoute: '/tools/ai-image-restoration',
    relatedRoutes: [
      '/tools/ai-video-restoration',
      '/tools/remove-background-from-image',
      '/tools/compress-image',
      '/tools/image-resizer',
    ],
    suggestedFutureRoutes: [],
    recommendedInternalLinks: [
      { label: 'AI Video Restoration', route: '/tools/ai-video-restoration', description: 'Restore and upscale a video snippet.' },
      { label: 'Remove background', route: '/tools/remove-background-from-image' },
      { label: 'Compress image', route: '/tools/compress-image' },
    ],
  },
  /* FFmpeg-education cluster hidden during AdSense review because every
     destination it pointed at lives under /blog. Re-enable alongside the
     blog when new posts are ready.
  {
    slug: 'ffmpeg-education',
    title: 'FFmpeg and media format education',
    primaryKeyword: 'FFmpeg tutorial',
    secondaryKeywords: [
      'how FFmpeg works',
      'video codec explained',
      'audio codec explained',
      'container vs codec',
    ],
    intent: 'informational',
    targetRoute: '/blog',
    relatedRoutes: [
      '/blog/video/video-compression-guide',
      '/blog/image/image-optimization-guide',
      '/blog/audio/audio-quality-guide',
    ],
    suggestedFutureRoutes: [
      '/guides/container-vs-codec',
      '/guides/ffmpeg-cheatsheet',
    ],
    recommendedInternalLinks: [
      { label: 'Browse the blog', route: '/blog' },
      {
        label: 'Video compression guide',
        route: '/blog/video/video-compression-guide',
      },
      {
        label: 'Audio quality guide',
        route: '/blog/audio/audio-quality-guide',
      },
    ],
  },
  */
];

export const KEYWORD_CLUSTER_MAP: Record<string, KeywordCluster> =
  KEYWORD_CLUSTERS.reduce(
    (acc, cluster) => {
      acc[cluster.slug] = cluster;
      return acc;
    },
    {} as Record<string, KeywordCluster>,
  );

export const getClusterBySlug = (slug: string): KeywordCluster | undefined =>
  KEYWORD_CLUSTER_MAP[slug];
