import { z } from 'zod';

export const imageConversionSchema = z.object({
  format: z.enum(['jpg', 'png', 'webp', 'gif']),
  width: z.number().min(1).max(4096).optional(),
  height: z.number().min(1).max(4096).optional(),
  quality: z.number().min(1).max(100).default(85),
  filter: z.enum(['none', 'grayscale', 'sepia', 'blur', 'sharpen', 'swirl', 'barrel-distortion', 'oil-painting', 'vintage', 'emboss', 'charcoal', 'sketch', 'rotate-45º', 'rotate-90º', 'rotate-180º', 'rotate-270º']).default('none'),
  tint: z.string().optional(),
  crop: z.object({
    x: z.number().min(0),
    y: z.number().min(0),
    width: z.number().min(1),
    height: z.number().min(1),
  }).optional(),
  textOverlay: z.object({
    text: z.string().max(500).optional(),
    size: z.number().min(8).max(512).optional(),
    color: z.string().optional(),
    strokeColor: z.string().optional(),
    strokeWidth: z.number().min(0).max(32).optional(),
    gravity: z.enum(['NorthWest', 'North', 'NorthEast', 'West', 'Center', 'East', 'SouthWest', 'South', 'SouthEast']).optional(),
    font: z.enum(['default', 'DejaVu-Sans', 'DejaVu-Serif', 'DejaVu-Sans-Mono', 'Liberation-Sans', 'Liberation-Serif', 'Liberation-Mono']).optional(),
    x: z.number().min(0).optional(),
    y: z.number().min(0).optional(),
  }).optional(),
  metadataMode: z.enum(['keep', 'strip', 'custom']).default('keep'),
  removeMetadata: z.boolean().optional(),
  metadata: z.object({
    title: z.string().max(1000).optional(),
    author: z.string().max(1000).optional(),
    description: z.string().max(1000).optional(),
    copyright: z.string().max(1000).optional(),
    comment: z.string().max(1000).optional(),
    keywords: z.string().max(1000).optional(),
    exifTiff: z.record(z.string()).optional(),
    gpsLocation: z.record(z.string()).optional(),
    iptc: z.record(z.string()).optional(),
    advanced: z.record(z.string()).optional(),
  }).optional(),
  gpsOptions: z.object({
    removeLocationData: z.boolean().optional(),
    replaceLocationData: z.boolean().optional(),
    latitude: z.number().min(-90).max(90).optional(),
    longitude: z.number().min(-180).max(180).optional(),
    altitude: z.number().optional(),
    roundLocationPrecision: z.boolean().optional(),
    precisionDecimals: z.number().min(0).max(8).optional(),
    removeCaptureDirection: z.boolean().optional(),
    removeGpsTimestamp: z.boolean().optional(),
    removeAltitude: z.boolean().optional(),
    removeDestinationFields: z.boolean().optional(),
  }).optional(),
  advancedTags: z.record(z.string()).optional(),
});
